// <auto-generated />
using System;
using Hackathon.Reports.Api.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hackathon.Reports.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hackathon.Reports.Api.Domain.Entities.PointRecordReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Registers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserIdentification")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentification");

                    b.HasIndex("UserIdentification", "Date")
                        .IsUnique();

                    b.ToTable("tb_point_record_report", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33f5eb34-b594-4853-a8c2-ca04f144718e"),
                            Date = new DateOnly(2024, 3, 1),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"18:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("4254f432-714e-4ba3-9fb8-a55cf9634828"),
                            Date = new DateOnly(2024, 3, 4),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("0e8f6443-6ffc-434f-bbe2-601094710d0d"),
                            Date = new DateOnly(2024, 3, 5),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("50900374-d272-4560-91a4-7c865e6b60c4"),
                            Date = new DateOnly(2024, 3, 6),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:30:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("be8e5ace-d07b-4c4f-bb11-47eb40741392"),
                            Date = new DateOnly(2024, 3, 7),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("7217b499-2e31-42c0-98a5-45341ddab1b0"),
                            Date = new DateOnly(2024, 3, 8),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("101ca83b-2020-404d-9fd7-d24beb8e2d0a"),
                            Date = new DateOnly(2024, 3, 11),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("6885ebf9-6dd0-4544-8a52-1deba7feae64"),
                            Date = new DateOnly(2024, 3, 12),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:10:00\"}, {\"StartTime\":\"13:10:00\",\"EndTime\":\"17:20:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("8e5d30bf-9d9b-49f4-ac09-8f612acc312c"),
                            Date = new DateOnly(2024, 3, 13),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:40:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("eb5fd3d9-2d6a-437f-97e4-50460fe17093"),
                            Date = new DateOnly(2024, 3, 14),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("31fc841a-6588-4987-bbde-dd475ba529cb"),
                            Date = new DateOnly(2024, 3, 15),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("51c70c16-cd5b-468b-adec-029e40b4faa5"),
                            Date = new DateOnly(2024, 3, 18),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("db858396-7aec-4027-aa42-af78475eb37b"),
                            Date = new DateOnly(2024, 3, 19),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:10:00\"}, {\"StartTime\":\"13:10:00\",\"EndTime\":\"17:20:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("3beb51d8-ab93-4838-aca8-023f7ab9368c"),
                            Date = new DateOnly(2024, 3, 20),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:40:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("019eaeac-88e2-47b7-a916-4d3d0fc0f60e"),
                            Date = new DateOnly(2024, 3, 21),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("546ac3f3-9176-464f-97b2-ef509987105a"),
                            Date = new DateOnly(2024, 3, 22),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("7064b744-6494-448c-8b52-fc2445b92269"),
                            Date = new DateOnly(2024, 3, 25),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("72e24965-2465-4dd9-9ec5-3335ae1fe253"),
                            Date = new DateOnly(2024, 3, 26),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:10:00\"}, {\"StartTime\":\"13:10:00\",\"EndTime\":\"17:20:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("77ed8db7-a1e3-4f36-b6c6-20996f53d2f8"),
                            Date = new DateOnly(2024, 3, 27),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:40:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("c4bc3010-ab68-46a5-a589-e47a98f7a17d"),
                            Date = new DateOnly(2024, 3, 28),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        },
                        new
                        {
                            Id = new Guid("bed63fc9-acdd-41fe-bdbe-3abb5e79946c"),
                            Date = new DateOnly(2024, 3, 29),
                            IsDeleted = false,
                            Registers = "[{\"StartTime\":\"08:00:00\",\"EndTime\":\"12:00:00\"}, {\"StartTime\":\"13:00:00\",\"EndTime\":\"17:00:00\"}]",
                            UserIdentification = "seed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
